name: flutter_food_app
description: A new Food Application

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# Read more about versioning at semver.org.
version: 1.0.0+1

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  pimp_my_button:
      git:
        url: git://github.com/Norbert515/pimp_my_button.git
  carousel_slider: ^1.1.0
  flutter_staggered_grid_view: ^0.2.7
  smooth_star_rating: ^1.0.1
  toast: ^0.1.3
  flutter_easyrefresh: ^1.2.7
  camera: 0.4.2
  flutter_masked_text: ^0.8.0
  font_awesome_flutter: ^8.4.0
  flutter_bloc: ^0.8.0
  shimmer: ^1.0.0
  flutter_xlider: ^2.2.0
  path_provider: 0.5.0+1
  image: ^2.1.3
  flutter_inner_drawer: ^0.2.5
  http: ^0.12.0+2
  flutter_spinkit: ^3.1.0
  file_picker: ^1.3.5
  firebase_storage: ^3.0.0
  firebase_core: ^0.4.0+1
  flutter_account_kit: ^0.6.6
  firebase_messaging: ^5.0.1+1
  connectivity: 0.4.0
  url_launcher: ^5.0.2
  share: ^0.6.1+1
  avatar_glow: ^0.2.0
  shared_preferences: 0.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  assets:
  #Images
    - assets/images/night.png
    - assets/images/morning.png
    - assets/images/logo.png

    - assets/images/discount_icon.png

    - assets/images/gifs/relax.gif
  #Data
    - assets/datas/vn_province.json
  fonts:
    - family: find
      fonts:
        - asset: assets/fonts/icons/find_icons.ttf
    - family: new
      fonts:
        - asset: assets/fonts/icons/new_icons.ttf
    - family: box
      fonts:
        - asset: assets/fonts/icons/box_icons.ttf
    - family: user
      fonts:
        - asset: assets/fonts/icons/user_icons.ttf
    - family: notification
      fonts:
        - asset: assets/fonts/icons/notification_icons.ttf
    - family: cart
      fonts:
        - asset: assets/fonts/icons/cart_icons.ttf
    - family: home
      fonts:
        - asset: assets/fonts/icons/home_icons.ttf
    - family: house
      fonts:
        - asset: assets/fonts/icons/house_icons.ttf
    - family: Montserrat
      fonts:
        - asset: assets/fonts/montserrat/Montserrat-Regular.ttf
        - asset: assets/fonts/montserrat/Montserrat-Medium.ttf
          weight : 400
        - asset: assets/fonts/montserrat/Montserrat-Italic.ttf
          style: italic
        - asset: assets/fonts/montserrat/Montserrat-Light.ttf
          weight: 200
        - asset: assets/fonts/montserrat/Montserrat-SemiBold.ttf
          weight: 500
        - asset: assets/fonts/montserrat/Montserrat-Bold.ttf
          weight: 700
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
